# -*- coding: utf-8 -*-
"""hac_clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1teHoFciyoPlb3rCPC7CX7AOgji1x_n-8
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage

def hac_single_linkage(dissimilarity_matrix):
    n = dissimilarity_matrix.shape[0]
    clusters = [[i] for i in range(n)]
    current_labels = list(range(n))
    linkage_matrix = []
    next_cluster_label = n
    D = dissimilarity_matrix.copy()
    while len(clusters) > 1:
        np.fill_diagonal(D, np.inf)
        i, j = np.unravel_index(np.argmin(D), D.shape)
        dist = D[i, j]
        new_cluster = clusters[i] + clusters[j]
        size = len(new_cluster)
        linkage_matrix.append([current_labels[i], current_labels[j], dist, size])
        new_distances = np.minimum(D[i, :], D[j, :])
        D = np.delete(D, [i, j], axis=0)
        D = np.delete(D, [i, j], axis=1)
        D = np.vstack([D, new_distances[:-2]])
        new_col = np.append(new_distances[:-2], np.inf)[:, np.newaxis]
        D = np.hstack([D, new_col])
        clusters.pop(max(i, j))
        clusters.pop(min(i, j))
        clusters.append(new_cluster)
        current_labels.pop(max(i, j))
        current_labels.pop(min(i, j))
        current_labels.append(next_cluster_label)
        next_cluster_label += 1
    return np.array(linkage_matrix)

DISSIMILARITY_MATRIX = np.array([
    [0.0, 2.0, 6.0, 10.0],
    [2.0, 0.0, 5.0, 9.0],
    [6.0, 5.0, 0.0, 4.0],
    [10.0, 9.0, 4.0, 0.0]
])

linkage_matrix_manual = hac_single_linkage(DISSIMILARITY_MATRIX)
print(linkage_matrix_manual)

plt.figure(figsize=(8,4))
dendrogram(linkage_matrix_manual)
plt.show()

linkage_scipy = linkage(DISSIMILARITY_MATRIX, method='single')
plt.figure(figsize=(8,4))
dendrogram(linkage_scipy)
plt.show()